server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: zhang20061023@
    driver-class-name: com.mysql.jdbc.Driver
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
race:
  jwt:
    user-secret-key: itheima
    user-token-name: authentication
    user-ttl: 7200000000000
  oauth2:
    client-id: fd645dd7bd720cf48d78fd5d379219147ac4863de9cc035aac22bec899305eac
    redirect-uri: http://localhost:8080/home
    client-secret: 77234637a903da0a54a8c00796bfc908d00e9bf6dd16fc6d73aa38dcc5d274c4
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  # ????XML????
  type-aliases-package: org.example.springsecurity.domain  # ??????
  # MyBatis-Plus 配置
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.springframework.security: DEBUG
